//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutorial.CustomMathFunction.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tutorial.CustomMathFunction.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add square two number.
        /// </summary>
        public static string Addition_Description {
            get {
                return ResourceManager.GetString("Addition_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition Square.
        /// </summary>
        public static string Addition_DisplayName {
            get {
                return ResourceManager.GetString("Addition_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First number.
        /// </summary>
        public static string Addition_FirstNumber_Description {
            get {
                return ResourceManager.GetString("Addition_FirstNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstNumber.
        /// </summary>
        public static string Addition_FirstNumber_DisplayName {
            get {
                return ResourceManager.GetString("Addition_FirstNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second number.
        /// </summary>
        public static string Addition_SecondNumber_Description {
            get {
                return ResourceManager.GetString("Addition_SecondNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecondNumber.
        /// </summary>
        public static string Addition_SecondNumber_DisplayName {
            get {
                return ResourceManager.GetString("Addition_SecondNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum and Square.
        /// </summary>
        public static string Addition_SumSquare_Description {
            get {
                return ResourceManager.GetString("Addition_SumSquare_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SumSquare.
        /// </summary>
        public static string Addition_SumSquare_DisplayName {
            get {
                return ResourceManager.GetString("Addition_SumSquare_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read html content to datatable.
        /// </summary>
        public static string HtmlResolver_Description {
            get {
                return ResourceManager.GetString("HtmlResolver_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HtmlResolver.
        /// </summary>
        public static string HtmlResolver_DisplayName {
            get {
                return ResourceManager.GetString("HtmlResolver_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First row is head for out put datatable field name.
        /// </summary>
        public static string HtmlResolver_FirstRowIsHeader_Description {
            get {
                return ResourceManager.GetString("HtmlResolver_FirstRowIsHeader_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Row Is Header.
        /// </summary>
        public static string HtmlResolver_FirstRowIsHeader_DisplayName {
            get {
                return ResourceManager.GetString("HtmlResolver_FirstRowIsHeader_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html string content .
        /// </summary>
        public static string HtmlResolver_HtmlContent_Description {
            get {
                return ResourceManager.GetString("HtmlResolver_HtmlContent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html Content.
        /// </summary>
        public static string HtmlResolver_HtmlContent_DisplayName {
            get {
                return ResourceManager.GetString("HtmlResolver_HtmlContent_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output datatable.
        /// </summary>
        public static string HtmlResolver_Result_Description {
            get {
                return ResourceManager.GetString("HtmlResolver_Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string HtmlResolver_Result_DisplayName {
            get {
                return ResourceManager.GetString("HtmlResolver_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read table position.
        /// </summary>
        public static string HtmlResolver_XPath_Description {
            get {
                return ResourceManager.GetString("HtmlResolver_XPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPath.
        /// </summary>
        public static string HtmlResolver_XPath_DisplayName {
            get {
                return ResourceManager.GetString("HtmlResolver_XPath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute)..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity timed out and was canceled..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value either for {0} or {1}, but not both..
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for both {0} and {1}..
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read xml file to datatable.
        /// </summary>
        public static string XmlResolver_Description {
            get {
                return ResourceManager.GetString("XmlResolver_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlResolver.
        /// </summary>
        public static string XmlResolver_DisplayName {
            get {
                return ResourceManager.GetString("XmlResolver_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read To Datatable.
        /// </summary>
        public static string XmlResolver_Result_Description {
            get {
                return ResourceManager.GetString("XmlResolver_Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string XmlResolver_Result_DisplayName {
            get {
                return ResourceManager.GetString("XmlResolver_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml file content.
        /// </summary>
        public static string XmlResolver_XmlString_Description {
            get {
                return ResourceManager.GetString("XmlResolver_XmlString_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlString.
        /// </summary>
        public static string XmlResolver_XmlString_DisplayName {
            get {
                return ResourceManager.GetString("XmlResolver_XmlString_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read xml node postion.
        /// </summary>
        public static string XmlResolver_XPath_Description {
            get {
                return ResourceManager.GetString("XmlResolver_XPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPath.
        /// </summary>
        public static string XmlResolver_XPath_DisplayName {
            get {
                return ResourceManager.GetString("XmlResolver_XPath_DisplayName", resourceCulture);
            }
        }
    }
}
